# ==============================
# --- OpenAI Configuration ---
# ==============================
#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gpt-4
#spring.ai.openai.chat.options.temperature=0.7
#spring.ai.openai.chat.options.max-tokens=1024


# ==============================
# --- Ollama Configuration ---
# ==============================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral:7b-instruct
spring.ai.ollama.chat.options.num-predict=150
spring.ai.ollama.chat.options.num-ctx=512
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.top-k=20
spring.ai.ollama.chat.options.top-p=0.9



# ==============================
# --- Database Configuration ---
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3307/aibox
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect